[package]
name = "starkvote"
version = "0.1.0"
edition = "2024_07"
license = "MIT"

[dependencies]
starknet = "2.14.0"
garaga = { path = "garaga/src" }

[cairo]
sierra-replace-ids = false
inlining-strategy = 2

[[target.starknet-contract]]
casm = true
casm-add-pythonic-hints = true
